{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "norn.fullname" . }}-api
  labels:
    {{- include "norn.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      {{- include "norn.componentSelectorLabels" (dict "root" . "component" "api") | nindent 6 }}
---
{{- end }}
{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "norn.fullname" . }}-web
  labels:
    {{- include "norn.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  maxUnavailable: {{ .Values.web.pdb.maxUnavailable }}
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      {{- include "norn.componentSelectorLabels" (dict "root" . "component" "web") | nindent 6 }}
{{- end }}
