apiVersion: v1
kind: Service
metadata:
  name: {{ include "norn.fullname" . }}-api
  labels:
    {{- include "norn.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "norn.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "norn.fullname" . }}-web
  labels:
    {{- include "norn.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "norn.componentSelectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: http
